#! /bin/bash
#===============================
#
# sdk_writer
#
# 2022/07/27 Kuninori Morimoto <kuninori.morimoto.gx@renesas.com>
#===============================
SCRIPT=`readlink -f "$0" | xargs dirname | xargs dirname | xargs dirname | xargs dirname`/script

${SCRIPT}/v3h_condor.py sdk
