#! /bin/bash
#===============================
#
# sdk_writer
#
# 2025/07/09 Kuninori Morimoto <kuninori.morimoto.gx@renesas.com>
#===============================
SCRIPT=`readlink -f "$0" | xargs dirname | xargs dirname | xargs dirname | xargs dirname`/script/python

${SCRIPT}/x5h_ironhide.py
