#!/usr/bin/expect
#====================================
#
# Renesas H3 StarterKit ROM Writer
#
# https://elinux.org/R-Car/Boards/H3SK#Quick_Start_How_To
#====================================
set dir [file dirname [file normalize [info script]]]
source $dir/lib

#
# check before run
#
argv_check
file_check $lists
mot_check $dir/../..
serial_number_check

#
# run minicom,
# move to CPLD mode
#
power_check
spawn minicom -D [lindex $argv 0]
cpld_mode $dir/../..

#
# Run Main
#
run_main $lists
