#! /bin/bash
#===============================
#
# yocto_writer
#
# 2022/03/28 Kuninori Morimoto <kuninori.morimoto.gx@renesas.com>
#===============================
SCRIPT=`readlink -f "$0" | xargs dirname | xargs dirname | xargs dirname | xargs dirname`/script

# reuse ebisu
${SCRIPT}/e3_ebisu.py d3_draak yocto
