#! /bin/bash
#===============================
#
# linux_bsp_writer
#
# 2022/07/27 Kuninori Morimoto <kuninori.morimoto.gx@renesas.com>
#===============================
SCRIPT=`readlink -f "$0" | xargs dirname | xargs dirname | xargs dirname`/script/python

${SCRIPT}/condor.py sdk
