#! /bin/bash
#===============================
#
# yocto_writer
#
# 2022/03/24 Kuninori Morimoto <kuninori.morimoto.gx@renesas.com>
#===============================
SCRIPT=`readlink -f "$0" | xargs dirname | xargs dirname | xargs dirname | xargs dirname`/script

${SCRIPT}/e3_ebisu.py e3_ebisu yocto
