#!/usr/bin/expect
# SPDX-License-Identifier: GPL-2.0
#====================================
#
# Renesas StarterKit Android fastboot setup
#
#====================================
set top [file dirname [file dirname [file normalize [info script]]]]
source $top/script/rom_writer.lib

set addr  [lindex $argv 0]
set time  [lindex $argv 1]
set tty   [lindex $argv 2]

proc erase_bootloader {} {
    sleep 1
    send "\003";	# Ctrl-C
    expect {
	"=>" { send "\r" }
    }
    expect {
	"=>" { send "mmc dev 1 1\r" }
    }
    expect {
	"=>" { send "mw.b 4f000000 0 200000\r" }
    }
    expect {
	"=>" { send "mmc write 4f000000 0 1000\r" }
    }
    expect {
	"=>" { send "mmc dev 1 2\r" }
    }
    expect {
	"=>" { send "mw.b 4f000000 0 200000\r" }
    }
    expect {
	"=>" { send "mmc write 4f000000 0 1000\r" }
    }
    expect {
	"=>" { send "reset\r" }
    }
    sleep 1
    send "\003";	# Ctrl-C
}

proc setenv {} {
    global addr
    global time

    expect {
	"=>" { send "env default -a\r" }
    }
    expect {
	"=>" { send "setenv ethaddr $addr\r" }
    }
    expect {
	# use vague number for serialno :)
	"=>" { send "setenv serialno 00009999\r" }
    }
    expect {
	"=>" { send "setenv bootargs video=LVDS-1:d video=VGA-1:d init_time=$time\r" }
    }
    expect {
	"=>" { send "saveenv\r" }
    }
    expect {
	"=>" { send "reset\r" }
    }
    sleep 1
    send "\003";	# Ctrl-C
}

proc start_fastboot {} {
    expect {
	"=>" { send "fastboot\r" }
    }
    expect "USB"
}

power_check "OFF"
power_check "ON"
spawn env LANG=C minicom -D $tty -b115200
erase_bootloader
setenv
start_fastboot
