#! /bin/sh
#===============================
#
# fastboot_hostpc
#
# 2021/10/20 Kuninori Morimoto <kuninori.morimoto.gx@renesas.com>
#===============================

#
# FIXME !!
#
# Some user don't need sudo here.
# But some user need it, otherwise fastboot.sh will fail.
#
sudo ./fastboot oem format
sudo ./fastboot reboot bootloader
sleep 3
sudo ./fastboot.sh --noresetenv
