#!/usr/bin/expect
# SPDX-License-Identifier: GPL-2.0
#====================================
#
# Renesas M3 StarterKit ROM Writer
#
# https://elinux.org/R-Car/Boards/M3SK#Quick_Start_How_To
#====================================
#
# load settings
#
source ${top}/linux/script/yocto/${ver}/m3

#
# check
#
file_check $lists
mot_check

#
# run minicom
#
before_minicom
spawn env LANG=C minicom -D $tty -b115200
after_minicom

#
# run main
#
run_main $lists
