#!/usr/bin/expect
# SPDX-License-Identifier: GPL-2.0
#====================================
#
# Renesas StarterKit ROM Writer
#
#====================================
set top [file dirname [file dirname [file dirname [file normalize [info script]]]]]
source $top/linux/script/rom_writer.lib

set soc  [lindex $argv 0]
set tgt  [lindex $argv 1]
set map  [lindex $argv 2]
set mode [lindex $argv 3]
set tty  [lindex $argv 4]

proc mot {} {
    global top
    return $top/linux/script/flash_writer/AArch32_output/AArch32_Flash_writer_SCIF_DUMMY_CERT_E6300400_ULCB.mot
}

proc cpld_mode {} {
    set mot [mot]

    sleep 1
    ctrl_c "=>"
    send "\r"
    expect {
	"=>" { send "cpld write 0x00 0x802181fe\r" }
    }
    expect {
	"=>" { send "cpld write 0x80 0x01\r" }
    }
    expect {
	"please send !"
    }
    upload_file $mot
    expect {
	">"
    }
}

proc before_minicom {} {
    global mode

    power_check "OFF"
    if {$mode == "sw"} {
	sw_change_mode dipswitch_h_update
    }
    power_check "ON"
}

proc after_minicom {} {
    global mode

    if {$mode == "sw"} {
	sw_change_back dipswitch_h_normal
    } else {
	cpld_mode
    }
}

source $top/linux/script/rom_writer.$soc

#
# check
#
file_check $lists

#
# run minicom
#
before_minicom
spawn env LANG=C minicom -D $tty -b115200
after_minicom
speed_up

#
# run main
#
run_main $lists
