#!/usr/bin/expect
# SPDX-License-Identifier: GPL-2.0
#====================================
#
# Renesas Salvator ROM Writer
#
#====================================
set top [file dirname [file dirname [file dirname [file normalize [info script]]]]]
source $top/../starterkit/linux/script/rom_writer.lib

set soc  [lindex $argv 0]
set tgt  [lindex $argv 1]
set map  [lindex $argv 2]
set tty  [lindex $argv 3]

proc before_minicom {} {
    power_check "OFF"
    sw_change_mode
    power_check "ON"
}

proc after_minicom {} {
    sw_change_back
}

source ${top}/linux/script/${tgt}/${map}/${soc}

#
# check
#
file_check $lists

#
# run minicom
#
before_minicom
spawn env LANG=C minicom -D $tty -b115200
after_minicom
speed_up

#
# run main
#
run_main $lists
