#! /bin/bash
#===============================
#
# android_writer
#
# 2022/01/19 Kuninori Morimoto <kuninori.morimoto.gx@renesas.com>
#===============================
SCRIPT=`readlink -f "$0" | xargs dirname | xargs dirname | xargs dirname`/script/python

# check fastboot command
if [ ! -f ./fastboot -o ! -f ./fastboot.sh ]; then
	echo "**** [error] ******************"
	echo "Android ROM Writer needs [fastboot] and [fastboot.sh]."
	echo "Assumes that you called this command from non-Android dir."
	echo "Please goto Android Binary dir, and call this command from there."
	echo "*******************************"
	exit
fi

${SCRIPT}/starterkit.py android
[ $? != 0 ] && exit

${SCRIPT}/starterkit.py android_fastboot
[ $? != 0 ] && exit

#
# FIXME !!
#
# Some user don't need sudo here.
# But some user need it, otherwise fastboot.sh will fail.
#
echo "+---------------------------+"
echo "| It requests sudo passward |"
echo "+---------------------------+"
sudo ./fastboot oem format
sudo ./fastboot reboot bootloader
sleep 3
sudo ./fastboot.sh --noresetenv
