#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
#===============================
#
# android_setup
#
# 2021/10/15 Kuninori Morimoto <kuninori.morimoto.gx@renesas.com>
#===============================
TOP=`readlink -f "$0" | xargs dirname`
TIME=`date +%s`
ADDR=$1
TTY=$2

#===============================
#
# check location / params
#
#===============================
if [ ! -f ./fastboot -o ! -f ./fastboot.sh ]; then
	echo "Run this command under Android ROM directory"
	exit
fi
if [ x${TTY} = x ]; then
	${TOP}/script/help ${TOP} android_setup
	exit
fi
if [[ ! ${ADDR} =~ [0-9a-f][0-9a-f]:[0-9a-f][0-9a-f]:[0-9a-f][0-9a-f]:[0-9a-f][0-9a-f]:[0-9a-f][0-9a-f]:[0-9a-f][0-9a-f] ]]; then
	echo "not Ether Mac address pattern"
	exit
fi
echo
echo "********************"
echo "USB x 2 cables connection OK ?"
echo ""
echo "Host PC <--> StarterKit side CN12 (for Serial = /dev/ttyUSBx)"
echo "Host PC <--> Kingfisher side CN13 (for ADB)"
echo "********************"
echo OK? \(y/n\)
read ANS
[ $ANS != y ] && exit

${TOP}/script/fastboot_uboot  ${ADDR} ${TIME} ${TTY}
[ $? != 0 ] && exit
${TOP}/script/fastboot_hostpc
