#! /bin/bash
#===============================
#
# rom_writer
#
# 2021/10/20 Kuninori Morimoto <kuninori.morimoto.gx@renesas.com>
#===============================
TOP=`readlink -f "$0" | xargs dirname`

#
# parse params
#
CHK=""
MOD=cpld # default
while getopts a:y:h OPT
do
	case $OPT in
		a) TGT=android
		   VER=$OPTARG
		   CHK="${CHK}1";;
		y) TGT=yocto
		   VER=$OPTARG
		   CHK="${CHK}1";;
		h) MOD=sw;;
		*) ${TOP}/scripts/help.sh && exit 1;;
	esac
done
shift $(expr $OPTIND - 1)

SOC=$1
TTY=$2
MAP=`grep "^${VER}:" ${TOP}/../${TGT}/table 2>/dev/null | awk -F ":" '{print $2}'`

if [ ! -d ${TOP}/script/${TGT}/${MAP} ]; then
	echo "run make first"
	exit
fi

if [ ! -e ${TTY} ]; then
	echo "no ${TTY} found"
	exit
fi

if [ x${SOC} = x -o \
     x${TTY} = x -o \
     x${MAP} = x -o \
     x${CHK} != x1 -o\
     ! -f ${TOP}/script/rom_writer.${SOC} ]; then
	${TOP}/script/help ${TOP} rom_writer
	exit
fi

${TOP}/script/rom_writer ${SOC} ${TGT} ${MAP} ${MOD} ${TTY}
