#! /bin/bash
#===============================
#
# rom_writer
#
# 2021/10/20 Kuninori Morimoto <kuninori.morimoto.gx@renesas.com>
#===============================
TOP=`readlink -f "$0" | xargs dirname`

SOC=$1
TGT=$2
VER=$3
MOD=$4
TTY=$5

if [ $# != 5  ]; then
	${TOP}/script/help ${TOP} rom_writer
	exit
fi

MAP=`grep "^${VER}:" ${TOP}/../${TGT}/table 2>/dev/null | awk -F ":" '{print $2}'`
if [ x${MAP} = x ]; then
	${TOP}/script/help ${TOP} rom_writer
	exit
fi

${TOP}/script/rom_writer ${SOC} ${TGT} ${MAP} ${MOD} ${TTY}
