#! /bin/bash
#===============================
#
# rom_writer
#
# 2021/10/20 Kuninori Morimoto <kuninori.morimoto.gx@renesas.com>
#===============================
TOP=`readlink -f "$0" | xargs dirname`
SCRIPT=${TOP}/../../starterkit/linux/script

#
# parse params
#
while getopts a:y: OPT
do
	case $OPT in
		a) TGT=android
		   VER=$OPTARG
		   CHK="${CHK}1";;
		y) TGT=yocto
		   VER=$OPTARG
		   CHK="${CHK}1";;
		*) ${SCRIPT}/help.sh && exit 1;;
	esac
done
shift $(expr $OPTIND - 1)


SOC=$1
TTY=$2
MAP=`grep "^${VER}:" ${TOP}/../${TGT}/table 2>/dev/null | awk -F ":" '{print $2}'`

if [ ! -d ${TOP}/script/${TGT}/${MAP} ]; then
	echo "run make first"
	exit
fi

if [ x${SOC} = x -o \
     x${TTY} = x -o \
     x${MAP} = x -o \
     x${CHK} != x1 -o\
     ! -f ${TOP}/script/${TGT}/${MAP}/${SOC} ]; then
	${SCRIPT}/help ${TOP} rom_writer
	exit
fi

if [ ! -e ${TTY} ]; then
	echo "no ${TTY} found"
	exit
fi

${TOP}/script/rom_writer ${SOC} ${TGT} ${MAP} ${TTY}
