#! /bin/bash
#===============================
#
# sdk_writer
#
# 2023/09/05 Kuninori Morimoto <kuninori.morimoto.gx@renesas.com>
#===============================
SCRIPT=`readlink -f "$0" | xargs dirname | xargs dirname | xargs dirname | xargs dirname`/script/python

${SCRIPT}/s4_spider.py sdk s4_sk
