#! /bin/bash
#===============================
#
# yocto_writer
#
# 2023/11/16 Kuninori Morimoto <kuninori.morimoto.gx@renesas.com>
#===============================
SCRIPT=`readlink -f "$0" | xargs dirname | xargs dirname | xargs dirname | xargs dirname`/script

${SCRIPT}/s4_spider.py yocto s4_sk
