#! /bin/bash
#===============================
#
# rom_writer
#
# 2022/02/25 Kuninori Morimoto <kuninori.morimoto.gx@renesas.com>
#===============================
SCRIPT=`readlink -f "$0" | xargs dirname | xargs dirname | xargs dirname | xargs dirname`/script

${SCRIPT}/s4_spider.py s4_spider
